services:
  ollama:
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - /tank/llm/ollama:/root/.ollama
    container_name: ollama
    image: docker.io/ollama/ollama:latest
    build: .
    pull_policy: always
    tty: true
    restart: unless-stopped
    ports:
      - 0.0.0.0:7869:11434
    environment:
      # - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_KEEP_ALIVE=-1
      - OLLAMA_FLASH_ATTENTION=1
      - OLLAMA_MAX_LOADED_MODELS=1
      # - OLLAMA_CONTEXT_LENGTH=4096
      - OLLAMA_KV_CACHE_TYPE=q4_0

      - BASE_MODEL=hf.co/unsloth/DeepSeek-R1-Distill-Llama-70B-GGUF:Q4_K_M
      - MODEL=quant_strategist

    deploy:
      resources:
        limits:
          cpus: '16'
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]