services:
  ollama:
    container_name: ollama
    image: docker.io/ollama/ollama:latest
    build: .
    pull_policy: always
    restart: unless-stopped
    tty: true
    volumes:
      - /tank/llm/ollama:/root/.ollama:z
    ports:
      - 0.0.0.0:7869:11434
    environment:
      - OLLAMA_KEEP_ALIVE=1h
      - OLLAMA_FLASH_ATTENTION=1
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_CONTEXT_LENGTH=1024
      - OLLAMA_KV_CACHE_TYPE=q4_0
    deploy:
      resources:
        limits:
          cpus: '16'
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
