name: Deploy Ollama Service

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy with Docker Compose
        run: |
          chmod +x ./entrypoint.sh

          docker compose pull
          docker compose down || true
          docker compose up -d