name: Deploy Ollama Service

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- ADD THIS DEBUGGING STEP ---
      - name: List files in workspace
        run: |
          echo "Verifying file existence and location:"
          ls -la
      # ------------------------------

      - name: Make entrypoint script executable
        run: chmod +x ./entrypoint.sh

      - name: Deploy with Docker Compose
        run: |
          docker compose pull
          docker compose down || true
          docker compose up -d