name: Deploy Ollama Service

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy with Docker Compose
        run: |
          docker compose pull
          docker compose down 
          docker compose up -d

      - name: Wait for Ollama to be ready
        run: |
          echo "Waiting for Ollama server to respond on port 7869..."
          timeout=120
          while ! curl -s http://z420:7869/ > /dev/null; do
            timeout=$((timeout - 1))
            if [ $timeout -le 0 ]; then
              echo "Error: Ollama server did not start in time."
              docker logs ollama
              exit 1
            fi
            sleep 1
          done
          echo "Ollama server is running."
      
      - name: Create From Modelfiles
        run: |
          echo "Creating models from Modelfiles..."

          docker exec ollama ollama create --from /Modelfiles/QuantStrategist
          docker exec ollama ollama create --from /Modelfiles/QuantDev

          echo "Models created successfully."
          